[project]
name = ""
version = "1.0"
authors = [
    {name="Drake Sanders", email="adsande4@go.olemiss.edu"},
]
description = "A package of user interface pages for NetMap"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [

]

[project.urls]
Homepage = ""
Issues = ""